// Profile specific components.
import "./core/application";
import "./core/header";
import "./core/footer";
import "./core/loading-indicator";
import "./core/page-not-found";
import "./core/modal";
import "./core/status-failed";
import "./core/status-loading";
import "./keyword-list/keyword-list";
import "./dataset-list/dataset-list";
import "./dataset-list/dataset-list-facet";
import "./dataset-list/dataset-list-facet-item";
import "./dataset-list/dataset-list-invalid-query";
import "./dataset-list/dataset-list-query/dataset-list-query";
import "./dataset-detail/dataset-detail";
import "./dataset-detail/dataset-detail-metadata";
import "./dataset-detail/dataset-detail-header";
import "./dataset-detail/dataset-detail-body";
import "./dataset-detail/dataset-detail-parts";
import "./dataset-detail/dataset-detail-descendants";
import "./dataset-detail/part-data-service";
import "./dataset-detail/part-distribution";
import "./dataset-detail/legal/legal-column";
import "./dataset-detail/legal/legal-column-czech";
import "./dataset-detail/legal/legal-column-dcatap";
import "./dataset-detail/legal/legal-column-missing";
import "./dataset-detail/access/endpoint-url-item";
import "./dataset-list/view-dataset/view-dataset";
import "./dataset-list/view-theme/view-theme";
import "./dataset-list/view-keyword/view-keyword";

// Styles.
import "bootstrap/dist/css/bootstrap.css";
import "./style.css";
import "./style-mode-default.css";
import "./style-mode-dark.css";

// Render.
import "../viewer-react/render";
